schema_version: 1

context:
  name: pikepdf
  version: "10.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 172611c32ab0a6097cfbccb397847b8e84d3f7bc7d32d5fc2f50e7e61f164725

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - scikit-build-core >=0.10
    - nanobind >=2.0
  run:
    - python
    - pillow >=10.0.1
    - deprecated
    - lxml >=4.8
    - packaging

tests:
  - python:
      imports:
        - pikepdf
      pip_check: true

about:
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  homepage: https://github.com/pikepdf/pikepdf
  repository: https://github.com/pikepdf/pikepdf
  documentation: https://pikepdf.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
    - carlodri
